### ISSUE TITLE
[FR] Only start processing the queue if there are X amount of items in the queue

### ISSUE THREAD

**Issue by BasToTheMax** [dzek69/queue-system#15]
Hi!
I am working on a discord bot with a queueing system, but I only want to start to process the queue if there are 25 or more items in the queue. How can I make this?

**Comment by dzek69** [comment]
Currently there is no way do to that, the jobs are run as soon as there is something to do.

How do you imagine your idea in details, I mean:
- if there is 25 items in the queue the queue should start and keep going until it reaches 0 jobs, then stop again, until it hits 25 again?
- what if it starts, goes down to 15 for example and there is 2 new jobs added (so it bumps to 17) - should those 2 jobs be left stopped until there is another batch of 25 jobs to do?

I can easily add the option to pause the queue, this way you can initialize the queue as paused, then with QUEUE_SIZE event you would be able to start the queue and pause it again when it reaches 0 jobs.

Batching the jobs to always contain 25 tasks would be a little bit more tricky and won't be implemented directly into the queue (or maybe as a helper util?), because you basically need a manager of queues for that (including the to-do pausing feature) - each queue would get up to 25 tasks and after one gets them it would just create another queue (that gets unpaused after the previous queue is empty & new queue gets 25 tasks)

BTW: IIRC the docs are a bit outdated, it doesn't say anything about types and has outdated stuff about using common js version (which now should work without the need for `dist` in path), but overall it should be up to date with how stuff works. I will try to update it with the change you need.

**Comment by BasToTheMax** [comment]
if the batch is running, and there are new jobs added, it will also run the new jobs.

Okay. So will you add this `pause` and `resume` function, so I can implement it myself?

**Comment by BasToTheMax** [comment]
Thanks for your fast response :D

**Comment by dzek69** [comment]
Hello again,
I just released 4.0.0 version with various improvements, including pause ability and updated documentation :)

The methods are called `pause`/`unpause`. I totally forgot to include them in the new docs though. Docs still needs a lot of rework.

**Comment by BasToTheMax** [comment]
Thanks for making this :D

**Comment by dzek69** [comment]
You're welcome, tell me if this works for you and I'll close this issue (or you should be able to close it yourself).
